const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--allow-loopback-in-peer-connection','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});try{
const pages=[];const errors=[];for(let i=0;i<3;i++){const context=await browser.newContext({viewport:i===1?{width:390,height:844}:{width:1366,height:900},permissions:['microphone','camera']});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8787/');pages.push(p);}const[a,b,c]=pages;
await a.click('#create-toggle');assert.equal(await a.locator('#create-toggle').isDisabled(),true);assert.equal(await a.locator('#create').textContent(),'Create');await a.fill('#name','Owner');await a.click('#create');await a.waitForSelector('#room:not([hidden])');const code=await a.locator('#room-code').textContent();await a.locator('#room-menu>summary').click();await a.selectOption('#room-capacity','10');await a.locator('#room-menu>summary').click();for(const p of[b,c]){await p.fill('#code',code);await p.locator('#join-form button').click();await p.waitForSelector('#room:not([hidden])');}
await b.fill('#message-input','Typing check');await a.waitForSelector('#typing:not([hidden])');await b.fill('#message-input','');await a.waitForFunction(()=>document.querySelector('#typing').hidden);console.log('PASS typing animation and clearing');
await b.fill('#message-input','@Ow');await b.getByRole('option',{name:'Owner',exact:true}).click();await b.fill('#message-input','Just between us');await b.locator('#chat-form button').click();await a.getByText('Just between us',{exact:true}).waitFor();await c.waitForTimeout(150);assert.equal(await c.getByText('Just between us',{exact:true}).count(),0);await c.reload();await c.waitForSelector('#room:not([hidden])');assert.equal(await c.getByText('Just between us',{exact:true}).count(),0);console.log('PASS @ private recipient and third-party refresh isolation');
await b.click('#clear-recipient');await b.click('#mic');await b.waitForFunction(()=>document.querySelector('#mic').getAttribute('aria-pressed')==='true');await b.click('#theater');assert.equal(await b.locator('.call-panel').isVisible(),false);await b.click('#toggle-vc');for(let i=0;i<3;i++){await a.fill('#message-input','Unread '+i);await a.locator('#chat-form button').click();}await b.waitForFunction(()=>document.querySelector('#chat-unread').textContent==='3');await b.click('#toggle-chat');assert.equal(await b.locator('#chat-unread').isVisible(),false);assert.equal(await b.locator('#mic').getAttribute('aria-pressed'),'true');
for(const viewport of [{width:390,height:844},{width:844,height:390},{width:1366,height:900}]){await b.setViewportSize(viewport);await b.waitForTimeout(100);const rects=await b.evaluate(()=>['watch-stage','.call-panel','.chat-panel'].map(id=>{const e=id[0]==='.'?document.querySelector(id):document.getElementById(id);const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};}));for(let i=0;i<rects.length;i++){const r=rects[i];assert.ok(r.width>0&&r.height>0);assert.ok(r.bottom<=viewport.height+1,JSON.stringify({viewport,rects}));for(let j=i+1;j<rects.length;j++){const q=rects[j];assert.ok(r.right<=q.x+1||q.right<=r.x+1||r.bottom<=q.y+1||q.bottom<=r.y+1,'Panels overlap');}}assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await b.screenshot({path:'/tmp/xparty-theatre-'+viewport.width+'.png'});}console.log('PASS independent theatre toggles, three-message badge, call preserved, nonoverlapping portrait/landscape/desktop layout');
await b.click('#theatre-settings');await b.selectOption('#theme-select','violet');await b.selectOption('#language-select','hi');assert.equal(await b.locator('#nav-home').textContent(),'होम');await b.selectOption('#language-select','kn');assert.equal(await b.locator('#nav-home').textContent(),'ಮುಖಪುಟ');await b.selectOption('#language-select','en');await b.locator('#settings-dialog .close-dialog').click();await b.reload();await b.waitForSelector('#room:not([hidden])');assert.equal(await b.locator('html').getAttribute('data-theme'),'violet');console.log('PASS theme and language settings');
await a.locator('#room-menu>summary').click();await a.click('#leave');await a.waitForSelector('#lobby:not([hidden])');await b.waitForFunction(()=>!document.querySelector('#lock').hidden);await a.fill('#code',code);await a.locator('#join-form button').click();await a.waitForSelector('#room:not([hidden])');await a.waitForFunction(()=>!document.querySelector('#lock').hidden);await b.waitForFunction(()=>document.querySelector('#lock').hidden);a.once('dialog',d=>d.accept());await a.locator('#room-menu>summary').click();await a.click('#end-room');await b.waitForSelector('#lobby:not([hidden])');await c.waitForSelector('#lobby:not([hidden])');console.log('PASS temporary host handoff, owner return, end room removes everyone');assert.deepEqual(errors,[]);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
